### ISSUE TITLE
bcmflash --ape does not fix the CRC

### ISSUE THREAD

**Issue by hughsie** [meklort/bcm5719-fw#108]
Doing something like `./bin/bcmflash -i Bcm5719_talos.bin -t file -a fw/ape-port2.bin` and then trying to flash the **new** `Bcm5719_talos.bin` doesn't work with fwupd as `FuBcm57xxFirmware` is checking the CRC of each code dictionary object which fails as the old CRC is being read from `the size of the old APE as defined in the header - 4` bytes.

**Comment by meklort** [comment]
This should be working now. Let me know if you see any other issues here.
