### ISSUE TITLE
ape-port0.bin maybe has invalid magic

### ISSUE THREAD

**Issue by hughsie** [meklort/bcm5719-fw#113]
I've just done this:

    sudo ./utils/bcmflash/bcmflash -t hardware -b binary

...this produced firmware.fw as expected. I exploded it out with some new tools in fwupd:

    sudo ./src/fwupdtool firmware-extract firmware.fw
    $ xxd id-ape.fw | head
    00000000: 1a4d 4342 0307 0700 4953 434e 302e 3130  .MCB....ISCN0.10
    00000010: 3931 2e31 0000 0000 0101 1300 0010 80c1  91.1............

...compared to:

    $ xxd bcm5719-fw-0.3.378-Linux-x86_64/fw/ape-port0.bin | head
    00000000: 4243 4d1a 0007 0703 6170 652d 706f 7274  BCM.....ape-port
    00000010: 3000 0000 0000 0000 017a 0300 9d09 1000  0........z......

looking more at firmware.fw:

    $ xxd firmware.fw
    ...
    000382e0: ffff ffff ffff ffff 1c74 a090 1a4d 4342  .........t...MCB
    000382f0: 0307 0700 4953 434e 302e 3130 3931 2e31  ....ISCN0.1091.1
    ...

...so it really does seem that the firmware is stored in BE representation (which would make sense, you don't want a file format that's host-endian).

Im guessing a bit, but I think `utils/elf2ape/main.cpp` has `ape.header.magic = APE_HEADER_MAGIC` and probably needs a `htonl` thrown in. If you agree with that logic, I'm happy to do a PR with that change.

**Comment by meklort** [comment]
You're correct that the firmware in NVM is in BE format. 

I though that I had bcmflash swap as appropriate, but it looks like you're correct that utils/elf2ape/main.cpp is the only one that swaps. I agree that a better place is elf2ape / ape2elf.

Note that bcmflash has https://github.com/meklort/bcm5719-fw/blob/master/utils/bcmflash/main.cpp#L503 which will likely need to be removed once elf2ape is correct.

If you do a pull request, I'll do some testing here to make sure everything works as expected and update as needed ensure it works on real hardware. If you'd prefer I can make the changes (probably tonight).

**Comment by hughsie** [comment]
> is the only one that swaps

Ohh! **Every** word is swapped! A good job I didn't try flashing it onto real hardware with fwupd :)

>  If you'd prefer I can make the changes

If it was just the header, I'd be within my depth; every word looks a bit more complicated to untangle and Ihave zero knowledge of the internal format. If you can handle this then great, thanks. I'm only supposed to be hacking on this stuff in my free time anyway :)

**Comment by meklort** [comment]
> Ohh! **Every** word is swapped! A good job I didn't try flashing it onto real hardware with fwupd :)

Fortunately even if you wrote it, there would not be a problem. Valid firmware is not required the device to come up.

> If it was just the header, I'd be within my depth; every word looks a bit more complicated to untangle and Ihave zero knowledge of the internal format. If you can handle this then great, thanks. I'm only supposed to be hacking on this stuff in my free time anyway :)
Sure thing. I'll take a look at it tonight.
