### ISSUE TITLE
bcmflash should report the current nvram stage1 version

### ISSUE THREAD

**Issue by hughsie** [meklort/bcm5719-fw#114]
I think it would be really helpful if bcmflash could report the current flash version as an additional command line option.

This is another way of asking if there is a way to get the stage1 version *without* unloading the module and dumping the entire flash, e.g. by reading the PCI config descriptor or doing some kind of ioctl to the opened device. I guess same question for the APE, although less important for my use case. Thanks!

**Comment by meklort** [comment]
There's a version register that should be updated by the firmware. You should be able to use bcmregtool to read this. I'll double check that it's being set properly by the stage1/APE code and let you know the sequence.

In any case, the proprietary firmware (stage1) has a pointer to a version string as the first or second word in flash. I don't have this, but I could add something compatible to stage1/ctr1.s to have an easy-to-find version string.

**Comment by hughsie** [comment]
> be able to use bcmregtool to read this

Is that GenFwVersion, i.e. `NVM 0x096; firmware version and upper 16 bits of manufacturing date`? Is so, that's not ideal as I have to unbind tg3 from the driver on every boot, dump the register, then rebind tg3 -- just to find out if there are any updates available on the system. If I could read this kind of register (or ask the kernel driver somehow) without binding BAR[0] that would be hugely preferable.

> has a pointer to a version string as the first or second word in flash

That would be an awesome feature to copy. Then fwupd can verify the firmware binary is actually matching the metadata value.

**Comment by meklort** [comment]
You can actually use ethtool to get this information (and read the nvm) without unbinding the driver.

Initial test code is here: https://github.com/meklort/bcm5719-fw/blob/iface/utils/bcmflash/iface.c

Note that right now the version field doesn't appear to be populated correctly with the free firmware, so I'll have to fix that.

**Comment by hughsie** [comment]
> You can actually use ethtool to get this information

Ohh, that's much easier that unloading modules. Do you think that you might implement writing using this API in the future? I wasn't entirely sure how you would choose the correct iface name for a given PCI device, but I'm not at all familiar with the ethtool interface.

> Initial test code is here

Looks good. I'll try it myself tomorrow.

> Note that right now the version field doesn't appear to be populated correctly with the free firmware

I assume it's _just_ ensuring that the linker puts a constant in the correct offset?

Richard

**Comment by hughsie** [comment]
> I'll try it myself tomorrow.

Seems to work here with tg3 loaded!

> Set from NVM 0x096; firmware version and upper 16 bits of manufacturing date.

Isn't that in the `info` section? or is it 0x28c+0x096 to put it in the stage1 section at a fixed offset?

**Comment by meklort** [comment]
> Do you think that you might implement writing using this API in the future? I wasn't entirely sure how you would choose the correct iface name for a given PCI device, but I'm not at all familiar with the ethtool interface.

I'm probably going to change the arguments on bcmflash a bit and cleanup the code. Basically I'm thinking i'll add a --probe argument that will print valid targets such as:
    0004:01:00.0     (iface enP4p1s0f0 access, as determined using ethtool)
    0004:01:00.1     (raw hardware access)

I'd then change -t to take the PCI bus if it's not a file:
-t 0004:01:00.1 or -t 0004:01:00.0.
If no -t argument is specified then I'd probably default to -probe.

For bcmregtool, the driver would have to be unloaded in most cases, but I can add a message about that. The same is probably true for apeconsole, but I might be able to use ethtool to read it w/o unloaded. I may look at that at some point.

If the pci bus has a driver loaded, I'd then use the ethtool interface for reading/writing, otherwise it'd use the raw access method.

> > Note that right now the version field doesn't appear to be populated correctly with the free firmware
> 
> I assume it's _just_ ensuring that the linker puts a constant in the correct offset?

It looks like this might be read from the VPD section for ethtool based on the tg3 source code, but I could be mistaken. Will need more investigation.

> Isn't that in the `info` section? or is it 0x28c+0x096 to put it in the stage1 section at a fixed offset?

I'm not sure. The info section won't be updated, so probably not good to pull version information from there.
 SHM.RcpuFwVersion.r32 is set by stage1 and could be used.
With the latest pull request referenced here, it's also possible to read the version string from the image easily.

**Comment by hughsie** [comment]
> use the ethtool interface for reading/writing

I didn't know you could write to the EEPROM using this interface; makes sense I suppose.

> The info section won't be updated, so probably not good to pull version information from there

Agree. I guess it suggests the nonfree updater doesn't preserve the entire info section and instead copies over important values from within it instead.

> SHM.RcpuFwVersion.r32

I guess we can get this from mmio (without tg3) but can we get the SHM values using the ethtool interface? Would that be a register read perhaps?

> it's also possible to read the version string from the image

This is less than ideal as it's a free form string that's difficult to parse. It's also not available from the tg3-less access, or is it at a fixed offset in NVRAM or something? Sorry for all the silly questions.

**Comment by meklort** [comment]
> > SHM.RcpuFwVersion.r32
> 
> I guess we can get this from mmio (without tg3) but can we get the SHM values using the ethtool interface? Would that be a register read perhaps?

Looking at the register dump form ethtool, this is not available.

> 
> > it's also possible to read the version string from the image
> 
> This is less than ideal as it's a free form string that's difficult to parse. It's also not available from the tg3-less access, or is it at a fixed offset in NVRAM or something? Sorry for all the silly questions.

When using tg3: nvram can be read using ethtool, so this should be OK.
When not using tg3, NVM can manually be read, agan, should be OK.

The version string (matching the proprietary firmware) has a pointer 8 bytes into stage1. This points to the actaully string and should be easy to parse (see flash for an example).
I've also gone ahead and updated byte 12 into stage1 with the version number itself so no parsing is really needed. On the proprietary firmware this is 0.

Note: The APE header also has a firmware string and a firmware version number, so I don't think any changes are needed there.
Let me know if that's sufficient for you of if any other changes are needed.

**Comment by hughsie** [comment]
> This points to the actaully string and should be easy to parse

I'm getting `5719-v1.43` for the Talos firmware... should that be rendered as `1.43.5719`?

**Comment by meklort** [comment]
5719-v1.43 is the version from the proprietary firmware, specifically firmware for the BCM5719, version 1.43 (major.minor only).
The free stage1 firmware will looks like stage1-0.4.391 - stage1 firmware, version 0.4.391. 
Also note that ethtool will now detect the stage1 firmware properly with the free firmware.

**Comment by hughsie** [comment]
Great, thanks. I've added the correct logic in fwupd to set the version format as appropriate.
