### ISSUE TITLE
APE fw crashing due to null pointer dereference of port->shm

### ISSUE THREAD

**Issue by wrffrz** [meklort/bcm5719-fw#14]
I'm currently running into an issue where after flashing stage1.bin with bcmflash and loading ape.bin with bcmregtool, apeconsole only prints out:

 Begin APE: 1
 Resetting channels...

... and never gets further.  After adding some additional debugging prints, I determined that it's hanging in resetChannel() because it tries to dereference a NULL pointer.

The value of port->shm when it reaches this point is zero, but the code is dereferencing this pointer and attempting to access variables at port->shm->NcsiChannelXXX without checking if shm is valid or not.

When I put a guard check in resetChannel(), the code gets further and reaches the point where it starts handling packets, but crashes in NCSI_handlePassthrough() for the same reason.  port->shm is NULL here also and dereferenced without checking its validity.

I can't find anywhere in the code where port->shm is actually initialized and there are lots of places where it's used without checking that the pointer is not NULL.

**Comment by meklort** [comment]
I have a number of fixes locally that include the issue you mentioned, I'll work on getting everything up to github soon.

**Comment by meklort** [comment]
The null pointer deref issue fix has been merged into master, as well as a number of other improvements.
