### ISSUE TITLE
Custom LLVM Compiling Issues

### ISSUE THREAD

**Issue by moriel5** [meklort/bcm5719-fw#241]
I seem to be having issues compiling the custom LLVM compiler, specifically compiling the Google unit tests.

```
[3922/3940] Building CXX object utils/unitt../gtest.dir/googletest/src/gtest-all.cc.o
ninja: build stopped: subcommand failed.
```
I have also had some things, such as terminfo and tininfo not found.

Might I not have all the necessary prerequisites installed?
If so, may I have a general idea of what needs to be installed to properly compile LLVM?

I am using Solus, however I believe I'll be able to figure out the eopkg package names.

**Comment by meklort** [comment]
That doesn't show the error message. Re-build with ninja -j1 and that should have error near the end of the output.

**Comment by moriel5** [comment]
It took me quite some time, due to a paint job that required me to take things out of my room (in a manner that prevented me from accessing either my desktop or my laptop in an orderly fashion), and then contracting CoVid (probably the Omicron variant, since it was extremely slight, and passed within a few days) right afterwards, delaying returning everything back, and just not having any time to work on this, however here are my results:

> [3923/3940] Building CXX object utils/bench...Files/benchmark.dir/benchmark_register.cc.o
FAILED: utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o 
/usr/bin/c++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/*REDACTED*/Compilations/BCM5719/llvm-project/build/utils/benchmark/src -I/*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src -I/usr/include/libxml2 -I/*REDACTED*/Compilations/BCM5719/llvm-project/build/include -I/*REDACTED*/Compilations/BCM5719/llvm-project/llvm/include -I/*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/include -I/*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/../include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wfloat-equal  -fstrict-aliasing  -fno-exceptions  -Wstrict-aliasing -O3 -DNDEBUG -std=c++14 -MD -MT utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o -MF utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o.d -o utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o -c /*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/benchmark_register.cc
In file included from /*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/benchmark_register.cc:15:
/*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/benchmark_register.h: In function ‘void AddRange(std::vector<T>*, T, T, int)’:
/*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:30: error: ‘numeric_limits’ is not a member of ‘std’
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                              ^~~~~~~~~~~~~~
/*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:46: error: expected primary-expression before ‘>’ token
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                                              ^
/*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:49: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                                                 ^~~
      |                                                 std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/include/benchmark/benchmark.h:175,
                 from /*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/internal_macros.h:4,
                 from /*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/check.h:8,
                 from /*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/benchmark_register.h:6,
                 from /*REDACTED*/Compilations/BCM5719/llvm-project/llvm/utils/benchmark/src/benchmark_register.cc:15:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
ninja: build stopped: subcommand failed.

**Comment by meklort** [comment]
If I recall correctly, the easiest way to fix this is to make sure you're using a recent OS. You can of course use an older version of LLVM, (look at the various meklort-x.x.x branches), but there is a chance that the resulting binary will function in all cases.

**Comment by moriel5** [comment]
Thanks, however as I am using a psuedo-rolling distro (rolling, but on a weekly basis, with emphasis on stability (not LTS, though that is an option for some packages)), Solus, and I make sure to keep it updated, I am pretty confident that it should be considered fairly recent (if not the latest versions, than almost the latest).

**Comment by meklort** [comment]
I tested out llvm 10.0.1, and it looks like it's an issue with that version of the compiler - it depends on certain header behavior that's no standard. I've fixed the branch and everything builds for me now in Fedora Rawhide.

My Talos II seems to have it's 5v rail fry on the mother board (and now fails to boot), so I'm working on fixing that, so I won't be able to help out too much so long as it's out of commission.

**Comment by moriel5** [comment]
Thanks, I'll look into it later today (I am currently on a hunt after the ThinkPad L14/L15 Gen1 schematics (Intel, but only because the AMD variant hadn't yet leaked)).

Oy, I hope you manage to repair that rail easily. I certainly understand.
By the way, whether it will be brought up by 3mdeb or not, I intend (no idea when, probably during one of the open discussion second) to point out your Firmware as part of my idea for a secure/trusted network device (mainly a small home server or firewall, in my case server/fiber router), together with their Dasharo firmware at their upcoming vPub.

I had already pitched the idea to them, what do you think?

And no, I won't be one of the speakers, this is just an idea I intend to bring up while there is free time.

**Comment by moriel5** [comment]
Will then, I am now able to compile the compiler without any issues, however I am having issues compiling the firmware, and again, the symptoms appear to be with the Google Tests.

Logs incoming once I have time to log in on my desktop (I really need to find time to familiarize myself with the Git workflow).

**Comment by meklort** [comment]
Closing the issue, please open a new one for gtest.

**Comment by moriel5** [comment]
No problem, I'll do so as soon as I log in from my desktop.
