### ISSUE TITLE
Unable to Compile Firmware

### ISSUE THREAD

**Issue by moriel5** [meklort/bcm5719-fw#247]
Distro: Solus
Ninja: 1.10.2

I seem to be having having issues compiling the firmware this time, specifically with the Google GMock Test unit (again).
Configuration with the custom LLVM Clang 10.0.1 seems to be fine (though sys/endian.h seems to be missing).

Error:
> /run/media/moriel/Compilations/BCM5719/bcm5719-fw/tests/googletest/googlemock/include/gmock/gmock-actions.h:137:10: fatal error: 'algorithm' file not found
#include <algorithm>

**Comment by meklort** [comment]
Looks like you don't have the std c++ development headers installed. (And possibly the libc headers for ednian.h).

**Comment by moriel5** [comment]
That is certainly odd, as I am pretty sure I do, however I'll recheck.

**Comment by moriel5** [comment]
I won't be online for the next 48 hours or so, so just a heads up on that.

**Comment by meklort** [comment]
I'm not sure, your package manager should have a way to find which package provides a file.

In any case I agree it's a bit odd. It could be related to LLVM 10 being a it older now. I am planning on updating to 14.x at some point, but right now it causes the firmware to fail to boot, and I haven't debugged it yet.o

**Comment by moriel5** [comment]
I believe it does, although I'm not completely sure, as packages are packaged with Solbuild, rather than eopkg. I'll try looking into that.

I hope you'll have the time to look into compiling the firmware with LLVM 14, and I hope I could be of use with that.

**Comment by moriel5** [comment]
It would appear that the `endian.h` header is included as part of the GCC package for Solus.

Also, oddly enough, despite the fact that I have `endian.h` in `/usr/include`, the compiler doesn't recognize it at all.

If it helps, I have GCC 12.1.0, as well as LLVM (and Clang) 13.0.1 installed (plus the compiled meklort-LLVM 10.0.1).

**Comment by meklort** [comment]
I've taken a look at this, and the custom llvm compiler isn't able to determine the system include path for libstdc++. You can force it by adding it to your environment like so for now:
export CPLUS_INCLUDE_PATH=/usr/include/c++/12/

I'm not sure if there's a simple way to change the llvm source code to add it, but this should work for llvm 10 at least.

**Comment by moriel5** [comment]
Interesting. I'll try that once I'm on my desktop and return with results.

**Comment by moriel5** [comment]
A bit late, however that certainly did the trick, and the firmware has been successfully compiled. Now I just need to find time to flash it.

Do I need to fear losing the MAC addresses? Or does BCMFlash take care of that for me?

**Comment by meklort** [comment]
If you only flash the ape / stage0, the mac address is preserved. If you flash the full fw image, it'll be overwritten.

That said, best bet is to backup the image using bcm flash in case if you ever want to go back to what was on there before. The readme should have details on how to do this.

**Comment by moriel5** [comment]
Thanks. Would you recommend eventually flashing the full image (after copying over to it the necessary information from the original firmware)? I have a CH341b (same thing as a CH341a) at the ready.

And yes, backing up the original firmware is pretty much a requirement in my opinion, and the instructions for doing so are indeed in the ReadMe.

**Comment by meklort** [comment]
For development, I usually flash the ape and stage0 separately - the bcmflash tool cannot rearrange sections right now, and so flashing the full image will result in being unable to update gust the ape code if it increases in size.

**Comment by moriel5** [comment]
Ah, thanks. I'll flash only the ape and stage0 then, for the time being.
