### ISSUE TITLE
BCM5719: Firmware broken

### ISSUE THREAD

**Issue by carlosgonz0** [meklort/bcm5719-fw#270]
I bought a blackbird one year ago but one week ago started using the Blackbird then i see that ethernet controller do not work, so after some troubleshootingis is seem that the firmware is broken maybe when raptor flashing to Libre firmware. Thanks

````
carlosgonz@blackbird:~$ sudo dmesg | grep tg3
[sudo] password for carlosgonz: 
[    0.799064] tg3 0004:01:00.0: enabling device (0140 -> 0142)
[    0.812710] tg3 0004:01:00.0: phy probe failed, err -19
[    0.817832] tg3 0004:01:00.0: Problem fetching invariants of chip, aborting
[    0.817895] tg3 0004:01:00.1: enabling device (0140 -> 0142)
[    0.832747] tg3 0004:01:00.1: phy probe failed, err -19
[    0.837893] tg3 0004:01:00.1: Problem fetching invariants of chip, aborting
[    0.837951] tg3 0004:01:00.2: enabling device (0140 -> 0142)
[    0.852716] tg3 0004:01:00.2: phy probe failed, err -19
[    0.857849] tg3 0004:01:00.2: Problem fetching invariants of chip, aborting
carlosgonz@blackbird:~$ lspci
```
 Openbmc console is has same output too.
 
 So the tg3 driver can not connect to controller so i looking to different way to reburning the firmware. Thanks

**Comment by carlosgonz0** [comment]
```
carlosgonz@blackbird:~$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: wlx00c0ca974766: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DORMANT group default qlen 1000
    link/ether 0x:c0:xx:9x:xxx6 brd ff:ff:ff:ff:ff:ff
carlosgonz@blackbird:~$

**Comment by meklort** [comment]
This looks like the MAC address wasn't embedded into the firmware image at the factory. See here: https://forums.raptorcs.com/index.php/topic,451.msg3674.html#msg3674

I suggest contacting Raptor and asking for the updated firmware image to get this fixed. I can also assist with dumping, modifying and reflashing, but the first step should be to contract Raptor for support.

**Comment by carlosgonz0** [comment]
> This looks like the MAC address wasn't embedded into the firmware image at the factory. See here: https://forums.raptorcs.com/index.php/topic,451.msg3674.html#msg3674
> 
> I suggest contacting Raptor and asking for the updated firmware image to get this fixed. I can also assist with dumping, modifying and reflashing, but the first step should be to contract Raptor for support.

Thanks i really  appreciate. So this mean that i need to wired the blackbird to recovery or it can be through TFTP ethernet   flashing?

**Comment by carlosgonz0** [comment]
I will come back here after Raptor Support. Thanks

**Comment by meklort** [comment]
Flashing isn't supported via TFTP, you'll need to get the firmware onto the blackbird via some other interface (usb or other network card), then use bcmflash (from this repo) to flash the firmware (the instructions on the forum will work).

The device can be flashed even with invalid firmware present, so no need to solder.

**Comment by carlosgonz0** [comment]
Hi @meklort
Can i set my custom mac address then building? if so where is located the file to write the MACs?


THANKS

**Comment by meklort** [comment]
No need to compile the firmware, you can dump, modify, and reflash with bcmflash. The --mac0/1/2/3 options allow you to modify the binary. You can also modify it in-place without saving to the file system first, but it's best to make a backup just in case.

**Comment by carlosgonz0** [comment]
> No need to compile the firmware, you can dump, modify, and reflash with bcmflash. The --mac0/1/2/3 options allow you to modify the binary. You can also modify it in-place without saving to the file system first, but it's best to make a backup just in caseAhoy

**Comment by carlosgonz0** [comment]
```
carlosgonzt@blackbird:/home/carlosgonz/Descargas/bcm5719-fw-0.6.12-Linux-ppc64le/bin# ./bcmflash -t raw -i enP4p1s0f0 --mac0=01:23:45:67:89:AB  --mac1=02:23:45:67:89:AB --mac2=03:23:45:67:89:AB 
Found supported device 14e4:1657 at /sys/bus/pci/devices//0004:01:00.1/config
mmaping BAR[0]: /sys/bus/pci/devices//0004:01:00.1/resource0
mmaping BAR[2]: /sys/bus/pci/devices//0004:01:00.1/resource2
mmaping BAR[4]: /sys/bus/pci/devices//0004:01:00.1/resource4
=== stage1 ===
Version:             Unknown (version 0.0.0)
Magic:               0x669955AA
Bootstrap Phys Addr: 0x08003800
Length (bytes):      0x00001420
Calculated CRC:      0x7E945336
CRC:                 0x02439024
Error: stage1 crc is invalid.
=== stage2 ===
Magic:               0x8F4301E4
Length (bytes):      0x2402FFDB
Segmentation fault (`core' generado)
```
Can you tell me the exact sintaxis of "modify and flash" the controller?

Thanks of advance.

**Comment by carlosgonz0** [comment]
```
arlosgonz@blackbird:~/Documentos/bcm5719-fw/build/utils/bcmflash$ sudo ./bcmflash -t raw -i enP4p1s0f0 -1 stage1-port2.bin
Found supported device 14e4:1657 at /sys/bus/pci/devices//0004:01:00.1/config
mmaping BAR[0]: /sys/bus/pci/devices//0004:01:00.1/resource0
mmaping BAR[2]: /sys/bus/pci/devices//0004:01:00.1/resource2
mmaping BAR[4]: /sys/bus/pci/devices//0004:01:00.1/resource4
=== stage1 ===
Version:             Unknown (version 0.0.0)
Magic:               0x669955AA
Bootstrap Phys Addr: 0x08003800
Length (bytes):      0x00001420
Calculated CRC:      0x7E945336
CRC:                 0x02439024
Error: stage1 crc is invalid.
Updating stage1 with contents of file stage1-port2.bin
Length is longer than original, currently unable to update.
```

**Comment by carlosgonz0** [comment]
Dear @meklort  can help me  a little more to tackle the issues what i showing?

Thanks of advance.

**Comment by madscientist159** [comment]
@carlosgonz0 It looks like you ended up with one of the handful of Blackbirds that came off of a partially set up line programmer last year due to a mix up at line start.  If you want to DM or Email me the serial number / MAC address of the board I can send over a pregenerated image with instructions to flash.  This was the only issue with the line programmer, and I had thought all of these were already handled, but if you didn't use it for a year that would explain why it's coming up now :wink:  Either way we'll get you going ASAP.

Thanks!

**Comment by carlosgonz0** [comment]
Thanks you @madscientist159 
I already sent an email with Serial numbers and Macs numbers to  tpearson@raptorengineering.com

Once again thanks for the support.

**Comment by carlosgonz0** [comment]
I still waiting for a respond from Raptor to fix this.

**Comment by carlosgonz0** [comment]
OK so yesterday  Timothy Raptor sent to me the firwmware and this FIXED the issue. I folllowed the Raptor instruction but for some reason do not worked, so what i did is:
gnu# ./bcmregtool -u
 gnu# ./bcmflash -t raw -i 1 -r bcm5719-Raptor.fw
 
 Special thanks to: @madscientist159

**Comment by carlosgonz0** [comment]
Hello friends, i reopened this issue because it happening something...that i not know.

The issue is that  BMC and Petitboot Ethernet Mac number is diferent from Mac that was burned.

```
*BMC*: root@blackbird:~# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether **00:00:00:00:0c:*73* brd ff:ff:ff:ff:ff:ff
3: sit0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
```
```
*HOST* carlosgonz@blackbird:~# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether **00:00:00:00:0c:*72* brd ff:ff:ff:ff:ff:ff
3: sit0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
```

**Comment by meklort** [comment]
BMC and Host mac adresss being off by one is expected behavior.

No BMC MAC address is included in the NVRAM, it is instead provided by the BMC flash itself, set via nvram arguments. Future version of this firmware may support including the BMC mac address in eeprom, but at present this is not supported.


See here for more details on how the BMC mac address is set: https://wiki.raptorcs.com/wiki/Talos_II/Firmware/Public_Beta#Instructions
